services:
  reso:
    network_mode: host
    build: .
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - reso-data:/data
    environment:
      RESO_DATABASE_PATH: /data/reso.db
      RESO_METRICS_DATABASE_PATH: /data/reso_metrics.db

volumes:
  reso-data:
